# Generated by Django 5.0.2 on 2024-03-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comet',
            name='name',
        ),
        migrations.AddField(
            model_name='comet',
            name='type_of_comet',
            field=models.CharField(default='line', max_length=200),
        ),
    ]
